import json,os,sys
p='security/pip-audit.json'
out='security/pip-audit-utf8.json'
if not os.path.exists(p):
    print('ERROR: pip-audit.json not found at',p); sys.exit(1)
with open(p,'rb') as f:
    b=f.read()
encs=['utf-8','utf-16','utf-16le','utf-16be']
for enc in encs:
    try:
        s=b.decode(enc)
        data=json.loads(s)
        with open(out,'w',encoding='utf-8') as fo:
            json.dump(data,fo,indent=2)
        print('DECODED',enc)
        break
    except Exception:
        continue
else:
    print('FAILED to decode pip-audit.json'); sys.exit(2)
# summarize
vuls=[]
for dep in data.get('dependencies',[]):
    for vuln in dep.get('vulns',[]):
        vuls.append({'package':dep.get('name'),'version':dep.get('version'),
                     'id':vuln.get('id'),'fixed_in':vuln.get('fix_versions',[]),
                     'summary':vuln.get('advisory','')})
summary_file='security/SCAN_SUMMARY.md'
with open(summary_file,'w',encoding='utf-8') as sf:
    sf.write('# Security scan summary\n\n')
    sf.write('Generated by scripts/normalize_and_summarize_scans.py\n\n')
    sf.write('## pip-audit findings\n\n')
    if not vuls:
        sf.write('- No vulnerabilities found by pip-audit\n')
    else:
        for v in vuls:
            sf.write(f"- {v['id']} — {v['package']} {v['version']} — fixes: {v['fixed_in']}\n  - {v['summary'][:300]}\n\n")
print('WROTE',summary_file)
